mongo_uri="mongodb+srv://nikola:taketwo@application.vd16a.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
# mongo_uri="mongodb://localhost:27017/"
# mongo_uri=""
database="activity"
outbox_collection="outbox"
application_data_profile="adp"
orders_collection="orders"
