version: "3.0"

services:
  # mongo1:
  #   image: mongo
  #   container_name: mongo1
  #   command: ["--replSet", "rs0", "--bind_ip_all", "--port", "30001"]
  #   volumes:
  #     - ./data/mongo-1:/data/db
  #   ports:
  #     - 30001:30001

  # mongo2:
  #   image: mongo
  #   container_name: mongo2
  #   command: ["--replSet", "rs0", "--bind_ip_all", "--port", "30002"]
  #   volumes:
  #     - ./data/mongo-2:/data/db
  #   ports:
  #     - 30002:30002

  # mongo3:
  #   image: mongo
  #   container_name: mongo3
  #   command: ["--replSet", "rs0", "--bind_ip_all", "--port", "30003"]
  #   volumes:
  #     - ./data/mongo-3:/data/db
  #   ports:
  #     - 30003:30003

  postgres:
    image: postgres:11
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  camunda_workflow:
    image: camunda/camunda-bpm-platform:7.13.0
    container_name: camunda_workflow_example
    depends_on:
      - postgres
    ports:
      - "8080:8080"
